wechatplaceholder:
  chats:
    imageUrl:  url1${random.int}
    title: title1
    newest: newest1
  contacts:
    imageUrl: contact1
    nickName: fanrui
  discovers:
    moments: moments
  me:
    weChatNickName: .
    getWeChatId: miao***
    weChatPay: weChatPay
    favorites: favorites
    myPosts: myPosts
    cardsAndOffers: cardsAndOffers
    stickerAndGallery: stickerAndGallery
    settings: setting